apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: external-logging
spec:
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: 5044
  selector:
    app: logstash
  type: ClusterIP