apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: core-backup
  namespace: kube-system
spec:
  schedule: "30 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
                    - ppc64le
                    - s390x
                  - key: master
                    operator: In
                    values:
                    - "true"
          containers:
          - name: etcddump
            image: ibmcom/etcd:3.2.24
            command: ["/bin/sh","-c","cat /certs/etcd-cert > client.pem; cat /certs/etcd-key > client-key.pem; cat /certs/etcd-ca > ca.pem; etcdctl --cert=client.pem --key=client-key.pem --cacert=ca.pem --endpoints https://$(ENDPOINT):4001 snapshot save /backup/etcd/etcd.$(date +%Y-%m-%d_%H:%M:%S).db"]
            env:
            - name: ENDPOINT
              value: "#ETCD-ENDPOINT"
            - name: ETCDCTL_API
              value: "3"
            volumeMounts:
            - mountPath: "/backup"
              name: backup
            - mountPath: "/certs"
              name: etcd-certs
          - name: mongodbdump
            image: ibmcom/icp-mongodb:4.0.5
            command: ["/bin/bash","-c","cat /certs/tls.crt certs/tls.key > mongo.pem; export PRIMARY=$(mongo --host rs0/mongodb:27017 --username admin --password $ADMIN_PASSWORD --authenticationDatabase admin --ssl --sslCAFile /ca/tls.crt --sslPEMKeyFile mongo.pem --eval=\"db.isMaster()['\"'primary'\"']\" | grep ^icp-mongodb-); mongodump --host $PRIMARY --username admin --password $ADMIN_PASSWORD --authenticationDatabase admin --ssl --sslCAFile /ca/tls.crt --sslPEMKeyFile mongo.pem --oplog --verbose --gzip --archive=/backup/mongodb/mongodb-backup-$(date +%Y-%m-%d_%H:%M:%S).gz"]
            env:
             - name: ADMIN_PASSWORD
               valueFrom:
                 secretKeyRef:
                   key: password
                   name: icp-mongodb-admin
            volumeMounts:
            - mountPath: "/backup"
              name: backup
            - mountPath: "/ca"
              name: cluster-ca
            - mountPath: "/certs"
              name: mongodb-certs
          tolerations:
          - effect: NoSchedule
            key: dedicated
            operator: Exists
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: core-backup
          - name: cluster-ca
            secret:
              secretName: cluster-ca-cert
          - name: mongodb-certs
            secret:
              secretName: icp-mongodb-client-cert 
          - name: etcd-certs
            secret:
              secretName: etcd-secret
          restartPolicy: Never