apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: logging-elk-snapshot
  namespace: kube-system
spec:
  schedule: "30 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
         affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: beta.kubernetes.io/arch
                   operator: In
                   values:
                   - amd64
                   - ppc64le
                   - s390x
                 - key: management
                   operator: In
                   values:
                   - "true"
          containers:
          - name: es-snapshot
            image: ibmcom/curl:4.2.0-f2
            command: ["/bin/bash","-c","curl -XPUT --cacert '/certs/ca.crt' --cert '/certs/curator.crt' --key '/certs/curator.key' -H 'Content-Type: application/json' -d '{\"indices\": \"$(INDICES)\", \"ignore_unavailable\": true,\"include_global_state\": false}' \"https://elasticsearch:9200/_snapshot/es_backup/snapshot_$(date +%Y-%m-%d_%H-%M-%S)?wait_for_completion=true\""]
            env:
            - name: INDICES
              value: "*"
            volumeMounts:
            - mountPath: /certs
              name: certs
              readOnly: true
          tolerations:
          - effect: NoSchedule
            key: dedicated
            operator: Exists
          volumes:
          - name: certs
            secret:
              defaultMode: 420
              secretName: logging-elk-certs
          restartPolicy: Never