apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: logging-elk-elasticsearch
    chart: ibm-icplogging-2.2.0
    component: data
    heritage: Tiller
    release: logging
    role: data
  name: logging-elk-data
  namespace: kube-system
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: logging-elk-elasticsearch
      component: data
      heritage: Tiller
      release: logging
      role: data
  serviceName: elasticsearch-data
  template:
    metadata:
      annotations:
        productID: none
        productName: Elasticsearch
        productVersion: 5.5.1
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        app: logging-elk-elasticsearch
        chart: ibm-icplogging
        component: data
        heritage: Tiller
        release: logging
        role: data
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
              - key: management
                operator: In
                values:
                - "true"
      containers:
      - command:
        - /bin/bash
        - /scripts/entrypoint.sh
        env:
        - name: ES_JAVA_OPTS
          value: -Xms2048m -Xmx2048m
        - name: CFG_BASEDIR
          value: /usr/share/elasticsearch
        - name: CA_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: caTruststorePassword
              name: logging-elk-elasticsearch-pki-secret
        - name: APP_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: appKeystorePassword
              name: logging-elk-elasticsearch-pki-secret
        image: fyre-31-1.icp:8500/ibmcom/icp-elasticsearch:5.5.1-f2
        imagePullPolicy: IfNotPresent
        name: es-data
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            memory: 4Gi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - mountPath: /usr/share/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - mountPath: /scripts
          name: entrypoint
        - mountPath: /usr/share/elasticsearch/config/tls
          name: certs
          readOnly: true
        - mountPath: /usr/share/elasticsearch/plugin-bundles
          name: plugin-bundle
        - mountPath: /usr/share/elasticsearch/backups
          name: backup
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - chown
        - 1000:1000
        - /usr/share/elasticsearch/backups
        image: fyre-31-1.icp:8500/ibmcom/icp-initcontainer:1.0.0
        imagePullPolicy: IfNotPresent
        name: chown
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/backups
          name: backup
      - command:
        - chmod
        - "777"
        - /data-dir
        image: fyre-31-1.icp:8500/ibmcom/icp-initcontainer:1.0.0
        imagePullPolicy: IfNotPresent
        name: chmod
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data-dir
          name: data
      - command:
        - /bin/sh
        - -c
        - sysctl -w vm.max_map_count=262144 && sed -i '/^vm.max_map_count /d' /etc/sysctl.conf
          && echo 'vm.max_map_count = 262144' >> /etc/sysctl.conf
        image: fyre-31-1.icp:8500/ibmcom/icp-initcontainer:1.0.0
        imagePullPolicy: IfNotPresent
        name: sysctl
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: fyre-31-1.icp:8500/ibmcom/elasticsearch-plugin-searchguard:2.0.0-f2
        imagePullPolicy: IfNotPresent
        name: plugin-bundle
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/plugin-bundles
          name: plugin-bundle
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: data.yml
            path: elasticsearch.yml
          name: logging-elk-elasticsearch-config
        name: config
      - configMap:
          defaultMode: 365
          items:
          - key: entrypoint.sh
            path: entrypoint.sh
          - key: install-plugin.sh
            path: install-plugin.sh
          - key: map-config.sh
            path: map-config.sh
          name: logging-elk-elasticsearch-entrypoint
        name: entrypoint
      - name: certs
        secret:
          defaultMode: 420
          secretName: logging-elk-certs
      - emptyDir: {}
        name: plugin-bundle
      - name: backup
        persistentVolumeClaim:
          claimName: logging-backup
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        app: logging-elk-elasticsearch
        chart: ibm-icplogging
        component: data
        heritage: Tiller
        release: logging
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 20Gi
      storageClassName: logging-storage-datanode