pipeline {
  agent none

  environment {
    MAJOR_VERSION = 1
  }
 

  stages {
    stage('Say Hello') {
      agent any

      steps {
        sayHello 'Awesome Student!'
      }
    }
    stage('Unit Tests') {
      agent {
        label 'apache'
      }
    }
    
}    
