language: go
go: 1.7.x

# allow for use of Docker-based workers
sudo: false

install:
    - go get -v -u github.com/constabulary/gb/...

before_script:
    - env | sort
    - ( cd bashbrew/go && gb build )
    - export PATH="$PWD/bashbrew/go/bin:$PATH"

script:
    - ./bashbrew/travis.sh
