---
name: "list_deployments"
runner_type: "run-python"
description: "List deployments for a GitHub repository"
enabled: true
entry_point: "list_deployments.py"
parameters:
  api_user:
    type: "string"
    description: "The API user"
    default: "{{action_context.api_user|default(None)}}"
  repository:
    type: "string"
    description: "The full (Organization|User)/repository path"
    required: true
  github_type:
    type: "string"
    description: "The type of github installation to target, if unset will use the configured default."
    default: ~
