apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elk-rolebinding
  namespace: elk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elk-clusterrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: elk