apiVersion: v1
kind: PersistentVolume
metadata:
  name: applogging-datanode-172.24.19.212
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: /var/lib/icp/applogging/elk-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 172.24.19.212
  persistentVolumeReclaimPolicy: Retain
  storageClassName: logging-storage-datanode