apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kibana-anyuid
  namespace: kibana-dedicated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-anyuid-clusterrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: kibana-dedicated