apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-sidecar-config
  namespace: sidecar
data:
  filebeat.yml: |-
    filebeat.prospectors:
    - input_type: log
      paths: '${LOG_DIRS}'
      exclude_lines: '${EXCLUDE_LINES:[]}'
      include_lines: '${INCLUDE_LINES:[]}'

      ignore_older: '${IGNORE_OLDER:0}'
      scan_frequency: '${SCAN_FREQUENCY:10s}'
      symlinks: '${SYMLINKS:true}'
      max_bytes: '${MAX_BYTES:10485760}'
      harvester_buffer_size: '${HARVESTER_BUFFER_SIZE:16384}'

      multiline.pattern: '${MULTILINE_PATTERN:^\s}'
      multiline.match: '${MULTILINE_MATCH:after}'
      multiline.negate: '${MULTILINE_NEGATE:false}'

    filebeat.config.modules:
      # Set to true to enable config reloading
      reload.enabled: true

    output.console:
      codec.format:
        string: '%{[message]}'

    logging.level: '${LOG_LEVEL:info}'