---
name: notify_chat
pack: nagios
description: Post to chat when nagios service state changes
enabled: false
trigger:
  type: nagios.service_state_change
criteria:
  trigger.attempt:
    pattern: 2
    type: gt
action:
  ref: chatops.post_message
  parameters:
    message: NAGIOS {{trigger.service}} ID:{{trigger.event_id}} STATE:{{trigger.state}}/{{trigger.state_type}}
      {{trigger.msg}}
    channel: '#general'
