apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-test
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rbd-storage-class
