apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: glusterfs
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-glusterfs
  labels:
    app: nginx-glusterfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-glusterfs
  template:
    metadata:
      labels:
        app: nginx-glusterfs
    spec:
      volumes:
      - name: demo-glusterfs-storage
        persistentVolumeClaim:
          claimName: glusterfs-pvc
      containers:
        - name: nginx-glusterfs-container
          image: nginx
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: demo-glusterfs-storage
