apiVersion: v1
kind: PersistentVolumeClaim
metadata
  name: test-nfs-client
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    storageClassName: nfs-client
