apiVersion: "config.istio.io/v1alpha2"
kind: listchecker
metadata:
  name: catalogwhitelist
spec:
  overrides: ["user"]
  blacklist: false
---
apiVersion: "config.istio.io/v1alpha2"
kind: listentry
metadata:
  name: catalogsource
spec:
  value: source.labels["app"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: checkfromuser
spec:
  match: destination.labels["app"] == "catalog"
  actions:
  - handler: catalogwhitelist.listchecker
    instances:
    - catalogsource.listentry
