apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: denyuserhandler
spec:
  status:
    code: 7
    message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyuserrequests
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denycustomer
spec:
  match: destination.labels["app"] == "catalog" && source.labels["app"]=="user"
  actions:
  - handler: denyuserhandler.denier
    instances: [ denyuserrequests.checknothing ]

