kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cataloguedb-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "example-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
