apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
  namespace: mogambo
spec:
  replicas: 3
  revisionHistoryLimit: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  minReadySeconds: 20
  paused: false
  template:
    metadata:
      labels:
        app: front-end
        role: ui
        tier: front
    spec:
      containers:
      - image: schoolofdevops/frontend:latest
        imagePullPolicy: Always
        name: front-end
        ports:
        - containerPort: 8079
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

