apiVersion: v1
kind: PersistentVolume
metadata:
  name: mynfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/kubernetes
    server: 192.168.12.10
