---
  host:
    description: "Host where Sensu API endpoint is running"
    type: "string"
    secret: false
    required: true
  port:
    description: "Sensu API port (default 4567)"
    type: "string"
    secret: false
    required: true
    default: 4567
  user:
    description: "Sensu integration user"
    type: "string"
    secret: false
    required: true
  pass:
    description: "Sensu integration password"
    type: "string"
    secret: true
    required: true
  ssl:
    description: "Set to true to use SSL"
    type: "boolean"
    secret: false
    required: false
    default: false
