---
description: 'Notification for GoPE - internet pass'
tags: []
type:
  ref: standard
  parameters:
enabled: false
name: GoPE_Notify_Internet_Pass
trigger:
  type: core.st2.webhook
  parameters:
    url: gope
criteria:
  trigger.body.status:
    pattern: pass
    type: eq
  trigger.body.group:
    pattern: internet
    type: eq
action:
  ref: chatops.post_message
  parameters:
    message: 'Group {{trigger.body.group}} is in the state: {{trigger.body.status}}'
    channel: '#general'
pack: clicrud
ref: clicrud.GoPE_Notify_Internet_Pass
uid: 'rule:clicrud:GoPE_Notify_Internet_Pass'

