---
  aws_access_key_id:
    description: "AWS access key to use."
    type: "string"
    secret: true
    required: true
  aws_secret_access_key:
    description: "AWS access secret to use."
    type: "string"
    secret: true
    required: true
  region:
    description: "AWS region to use."
    type: "string"
    required: true
    default: 'us-east-1'
